import * as crypto from 'crypto';
import { QrCompletionPattern, QrHashPiece } from '../types';

/**
 * Service for managing the QR completion pattern and hash generation.
 */
export class QrHashService {
  private static TOKEN_GENERATED_INTERVAL = 10;
  private static TOKEN_RECEIVED_INTERVAL = 2;

  /**
   * Populates the QR pattern with the required hashes that the model must generate.
   * The hash for each piece is determined by its sequence in the grid.
   * 
   * @param pattern The initialized QrCompletionPattern.
   * @returns The pattern with all required hashes filled in.
   */
  public populateRequiredHashes(pattern: QrCompletionPattern): QrCompletionPattern {
    let step = 1;
    for (let y = 0; y < pattern.dimensions[1]; y++) {
      for (let x = 0; x < pattern.dimensions[0]; x++) {
        const tokensGenerated = step * QrHashService.TOKEN_GENERATED_INTERVAL;
        const tokensReceived = step * QrHashService.TOKEN_RECEIVED_INTERVAL;
        pattern.grid[y][x].requiredHash = this.generateHash(tokensGenerated, tokensReceived);
        step++;
      }
    }
    return pattern;
  }

  /**
   * Processes the current token state, generates a hash if thresholds are met,
   * and attempts to fill the next piece of the QR pattern.
   * 
   * @param pattern The current QrCompletionPattern.
   * @param tokensGenerated The total tokens generated so far.
   * @param tokensReceived The total tokens received so far.
   * @returns The updated QrCompletionPattern.
   */
  public processTokenFlow(pattern: QrCompletionPattern, tokensGenerated: number, tokensReceived: number): QrCompletionPattern {
    // Find the next piece that needs a provided hash
    let nextPiece: QrHashPiece | null = null;
    let filledCount = 0;
    const totalPieces = pattern.dimensions[0] * pattern.dimensions[1];

    for (let y = 0; y < pattern.dimensions[1]; y++) {
      for (let x = 0; x < pattern.dimensions[0]; x++) {
        const piece = pattern.grid[y][x];
        if (piece.providedHash === null) {
          if (nextPiece === null) {
            nextPiece = piece;
          }
        } else {
          filledCount++;
        }
      }
    }

    if (nextPiece) {
      // Determine the 'step' for hash generation based on how many pieces are already filled
      const currentStep = filledCount + 1;
      const requiredTokensGenerated = currentStep * QrHashService.TOKEN_GENERATED_INTERVAL;
      const requiredTokensReceived = currentStep * QrHashService.TOKEN_RECEIVED_INTERVAL;

      // Only generate and apply a hash if the token counts have reached the next interval
      if (tokensGenerated >= requiredTokensGenerated && tokensReceived >= requiredTokensReceived) {
        const providedHash = this.generateHash(requiredTokensGenerated, requiredTokensReceived);
        nextPiece.providedHash = providedHash;
        
        if (nextPiece.requiredHash === providedHash) {
          nextPiece.isFilled = true;
          filledCount++; // Increment count as we just filled one
        }
      }
    }

    // Recalculate completion rate
    pattern.completionRate = (filledCount / totalPieces) * 100;

    return pattern;
  }


  /**
   * Generates a SHA-256 hash based on the token counts.
   * This simulates the hash generation from the model's token flow.
   * 
   * @param tokensGenerated The number of tokens generated by the model.
   * @param tokensReceived The number of tokens received by the model.
   * @returns A SHA-256 hash string.
   */
  public generateHash(tokensGenerated: number, tokensReceived: number): string {
    const data = `gen:${tokensGenerated}-rec:${tokensReceived}`;
    return crypto.createHash('sha256').update(data).digest('hex');
  }

  /**
   * Initializes a new QR completion pattern with the specified dimensions.
   * 
   * @param width The width of the QR grid.
   * @param height The height of the QR grid.
   * @returns An un-filled QrCompletionPattern.
   */
  public initializeQrPattern(width: number, height: number): QrCompletionPattern {
    const grid: QrHashPiece[][] = [];

    for (let y = 0; y < height; y++) {
      const row: QrHashPiece[] = [];
      for (let x = 0; x < width; x++) {
        row.push({
          position: [x, y],
          requiredHash: null, // To be filled in later
          providedHash: null,
          isFilled: false,
        });
      }
      grid.push(row);
    }

    return {
      dimensions: [width, height],
      grid,
      completionRate: 0,
    };
  }
}
